### ISSUE TITLE
drmOpen(vc4) failed

### ISSUE THREAD

**Issue by jvcleave** [6by9/drm_mmal#4]
getting this error when trying to run on an RPi4

`ERROR(drm_mmal.c:690) : drmOpen(vc4) failed: No such file or directory`

**Comment by 6by9** [comment]
Are you running X? The master branch is intended to run in console mode, the x11 branch is for X.

DRM supports a single client at a time, and any additional clients that try to open the device will fail. X will be the first client registered.

**Comment by jvcleave** [comment]
I don't believe I was but will double check. It would have been from an SSH session - would that make a difference?

**Comment by 6by9** [comment]
If you've got X running on the device then yes.
Also ensure you haven't disabled OpenGL and KMS by commenting out "dtoverlay=vc4-fkms-v3d" from config.txt.

I've checked out a clean copy of master and it's run fine with the Big Buck Bunny test clip that is in /opt/vc/src/hello_pi/hello_video

**Comment by jvcleave** [comment]
got it!

`dtoverlay=vc4-fkms-v3d` was commented out (probably by default as I hadn't changed it)

Thanks!

**Comment by 6by9** [comment]
```dtoverlay=vc4-fkms-v3d``` is under a conditional block for the PI4 by default with Raspbian Buster. I can't speak for other distributions.
