### ISSUE TITLE
vcos error, no video

### ISSUE THREAD

**Issue by oomek** [6by9/drm_mmal#5]
Not sure what I'm doing wrong, I'm getting the following error after start decoding:
`vcos_semaphore_wait_timeout failed - status 1`

RPI4 - latest fw
vc4-kms-v3d-pi4

**Comment by 6by9** [comment]
Which branch?
You've provided it the path to an H264 elementary stream with Annex B startcodes? eg ```./drm_mmal /opt/vc/src/hello_pi/hello_video/test.h264```?

**Comment by oomek** [comment]
Right, I forgot about that tiny detail that I need to process containers myself. Working fine, thanks.
